# syntax = docker/dockerfile:experimental
# https://docs.docker.com/engine/reference/builder/
# https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/experimental.md
FROM registry.fedoraproject.org/fedora:29
ARG CLEAN_CACHE=true
ARG AGENT_VERSION=2.152.0
ARG AGENT_OS=linux
ARG AGENT_ARCH=x64

RUN echo mark-001

# https://dnf.readthedocs.io/en/latest/command_ref.html
# https://dnf.readthedocs.io/en/latest/conf_ref.html
RUN \
	echo CLEAN_CACHE=${CLEAN_CACHE} && \
	ls -l /var/cache/ && \
	sed -E -i 's/^\s*metadata_expire\s*=.*$/metadata_expire=never/g' /etc/yum.repos.d/* && \
	echo 'metadata_expire=never' >> /etc/dnf/dnf.conf && \
	echo 'keepcache=True' >> /etc/dnf/dnf.conf && \
	echo 'fastestmirror=True' >> /etc/dnf/dnf.conf && \
	dnf install -y \
		busybox \
		icu \
		compat-openssl10 \
	&& \
	$(${CLEAN_CACHE} || echo "echo CLEAN_CACHE=${CLEAN_CACHE} SKIPPING: ") dnf clean all && \
	true

ARG GROUP_NAME=azrpa
ARG GROUP_ID=29942
ARG USER_NAME=azrpa
ARG USER_ID=29942

RUN \
	echo CLEAN_CACHE=${CLEAN_CACHE} && \
	ls -l /var/cache/ && \
	echo groupadd -g ${GROUP_ID} ${GROUP_NAME} && \
	groupadd -g ${GROUP_ID} ${GROUP_NAME} && \
	echo useradd -M -d /var/opt/vsts-agent/ -s /sbin/nologin -g ${GROUP_NAME} -u ${USER_ID} ${USER_NAME} && \
	useradd -M -d /var/opt/vsts-agent/ -s /sbin/nologin -g ${GROUP_NAME} -u ${USER_ID} ${USER_NAME} && \
	mkdir -p /var/opt/vsts-agent/ /opt/vsts-agent/ && \
	chown -R ${USER_NAME}:${GROUP_NAME} /var/opt/vsts-agent/ /opt/vsts-agent/ && \
	ls -l /var/cache/ && \
	true

RUN \
	echo CLEAN_CACHE=${CLEAN_CACHE} && \
	ls -l /var/cache/ && \
	{ [ -e /var/cache/vsts-agent-${AGENT_OS}-${AGENT_ARCH}-${AGENT_VERSION}.tar.gz ] || busybox wget -c -O /var/cache/vsts-agent-${AGENT_OS}-${AGENT_ARCH}-${AGENT_VERSION}.tar.gz https://vstsagentpackage.azureedge.net/agent/2.152.0/vsts-agent-${AGENT_OS}-${AGENT_ARCH}-${AGENT_VERSION}.tar.gz; } && \
	busybox tar -xf /var/cache/vsts-agent-${AGENT_OS}-${AGENT_ARCH}-${AGENT_VERSION}.tar.gz -C /opt/vsts-agent/ && \
	chown -R ${USER_NAME}:${GROUP_NAME} /opt/vsts-agent/ && \
	$(${CLEAN_CACHE} || echo "echo SKIPPING: ") rm -v /var/cache/vsts-agent-${AGENT_OS}-${AGENT_ARCH}-${AGENT_VERSION}.tar.gz && \
	ls -l /var/cache/ && \
	true

COPY common-files/profile-vsts-agent.sh /etc/profile.d/vsts-agent.sh
COPY common-files/vsts-script.sh /opt/vsts-agent/bin/
RUN ln -s vsts-script.sh /opt/vsts-agent/bin/vsts-start.sh
ENV PATH /opt/vsts-agent/bin:$PATH

USER ${USER_NAME}:${GROUP_NAME}
WORKDIR /var/opt/vsts-agent/
VOLUME /var/opt/vsts-agent/

#ENTRYPOINT ["/opt/vsts-agent/bin/vsts-entrypoint.sh"]

CMD ["vsts-script.sh", "start"]
